/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/// Taken from `https://en.cppreference.com/w/cpp/keyword`
/// Some experimental keywords were filtered out and the resulting list was
/// sorted using a rust program.
const RESERVED_KEYWORDS: &[&str] = &[
    "alignas",
    "alignof",
    "auto",
    "bool",
    "break",
    "case",
    "catch",
    "char",
    "char16_t",
    "char32_t",
    "char8_t",
    "class",
    "const",
    "const_cast",
    "consteval",
    "constexpr",
    "continue",
    "decltype",
    "default",
    "delete",
    "do",
    "double",
    "dynamic_cast",
    "else",
    "enum",
    "explicit",
    "export",
    "extern",
    "false",
    "float",
    "for",
    "friend",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "mutable",
    "namespace",
    "new",
    "noexcept",
    "nullptr",
    "operator",
    "private",
    "protected",
    "public",
    "register",
    "reinterpret_cast",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "static_assert",
    "static_cast",
    "struct",
    "switch",
    "template",
    "this",
    "thread_local",
    "throw",
    "true",
    "try",
    "typedef",
    "typename",
    "union",
    "unsigned",
    "using",
    "virtual",
    "void",
    "volatile",
    "wchar_t",
    "while",
];

pub fn escape(rust_identifier: &mut String) {
    if RESERVED_KEYWORDS
        .binary_search(&rust_identifier.as_ref())
        .is_ok()
    {
        rust_identifier.push('_');
    }
}

/// All reserved keywords in C#, both normal and contextual.
const RESERVED_KEYWORDS_CSHARP: &[&str] = &[
    "abstract",
    "add",
    "alias",
    "allows",
    "and",
    "args",
    "as",
    "ascending",
    "async",
    "await",
    "base",
    "bool",
    "break",
    "by",
    "byte",
    "case",
    "catch",
    "char",
    "checked",
    "class",
    "const",
    "continue",
    "decimal",
    "default",
    "delegate",
    "descending",
    "do",
    "double",
    "dynamic",
    "else",
    "enum",
    "equals",
    "event",
    "explicit",
    "extension",
    "extern",
    "false",
    "field",
    "file",
    "finally",
    "fixed",
    "float",
    "for",
    "foreach",
    "from",
    "get",
    "global",
    "goto",
    "group",
    "if",
    "implicit",
    "in",
    "init",
    "int",
    "interface",
    "internal",
    "into",
    "is",
    "join",
    "let",
    "lock",
    "long",
    "managed",
    "nameof",
    "namespace",
    "new",
    "nint",
    "not",
    "notnull",
    "nuint",
    "null",
    "object",
    "on",
    "operator",
    "or",
    "orderby",
    "out",
    "override",
    "params",
    "partial",
    "private",
    "protected",
    "public",
    "readonly",
    "record",
    "ref",
    "remove",
    "required",
    "return",
    "sbyte",
    "scoped",
    "sealed",
    "select",
    "set",
    "short",
    "sizeof",
    "stackalloc",
    "static",
    "string",
    "struct",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "uint",
    "ulong",
    "unchecked",
    "unmanaged",
    "unsafe",
    "ushort",
    "using",
    "value",
    "var",
    "virtual",
    "void",
    "volatile",
    "when",
    "where",
    "while",
    "with",
    "yield",
];

pub fn escape_csharp(rust_identifier: &mut String) {
    if RESERVED_KEYWORDS_CSHARP
        .binary_search(&rust_identifier.as_ref())
        .is_ok()
    {
        rust_identifier.insert(0, '@');
    }
}

pub fn escape_config(rust_identifier: &mut String, config: &crate::Config) {
    #[cfg(feature = "csharp")]
    {
        if config.language == crate::bindgen::Language::CSharp {
            escape_csharp(rust_identifier);
        } else {
            escape(rust_identifier);
        }
    }

    #[cfg(not(feature = "csharp"))]
    {
        escape(&mut field.name);
    }
}
